import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>monti.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my page!
        </h1><br></br>

        <p className={styles.arial}>
          Hi, my name is Maurizio, and I'm messing around with this code thing...
        </p>

        <div className={styles.grid}>
          <a href="/about" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>Career overview.</p>
          </a>

          <a href="/projects" className={styles.card}>
            <h2>Projects &rarr;</h2>
            <p>My project page. Just a collection of apps using different building blocks.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://nextjs.org/learn"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Learn about Next.js in an interactive course with quizzes!</p>
          <span className={styles.arial}>
            <Image src="" alt="" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
